Update log_signatures.yml

diff --git a/.github/workflows/log_signatures.yml b/.github/workflows/log_signatures.yml
--- a/.github/workflows/log_signatures.yml
+++ b/.github/workflows/log_signatures.yml
@@ -29,6 +29,10 @@ jobs:
       run: |
         git config --global user.name "github-actions"
         git config --global user.email "github-actions@users.noreply.github.com"
-        git add signatures.csv
-        git commit -m "Update log $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
-        git push
+        if [ -f signatures.csv ]; then
+           git add signatures.csv
+           git commit -m "Update log $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
+           git push
+        else
+           echo "signatures.csv not found, skipping commit."
+         fi
